apiVersion: v1
kind: Secret
metadata:
  namespace: builder
  name: builder-secret
type: Opaque
data:

  REDIS_HOST: <REDIS_HOST>
  REDIS_PORT: <REDIS_PORT>
  REDIS_USERNAME: <REDIS_USERNAME>
  REDIS_PASSWORLD: <REDIS_PASSWORLD>

  AWS_ACCESS_KEY_ID:  <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
  AWS_CLOUDWATCH_LOG_NAME: <AWS_CLOUDWATCH_LOG_NAME>
  AWS_CLOUDWATCH_LOG_STREAM_NAME: <AWS_CLOUDWATCH_LOG_STREAM_NAME>


