apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: try-out-script
  name: try-out-script-deployment
  labels:
    app: try-out-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: try-out-script
  template:
    metadata:
      labels:
        app: try-out-script
    spec:
      containers:
      - name: try-out-script
        image: registry.digitalocean.com/code-executor/code-executor-try-out-script:<IMAGE_VERSION>
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: try-out-script-configmap
        - secretRef:
            name: try-out-script-secret
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
