apiVersion: v1
kind: Secret
metadata:
  namespace: try-out-script
  name: try-out-script-secret
type: Opaque
data:
  REDIS_HOST: <REDIS_HOST>
  REDIS_PORT: <REDIS_PORT>
  REDIS_USERNAME: <REDIS_USERNAME>
  REDIS_PASSWORLD: <REDIS_PASSWORLD>


