name: "Deploy application in Kubernetes"

on:
  push:
    branches:
      - master
  
jobs:


  build-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build api container image
      run: |
        cd api
        docker build -f Dockerfile -t ${{ secrets.DIGITALOCEAN_DOCKER_REGISTRY }}/code-execute-api:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push backend image to DigitalOcean Container Registry
      run:  docker push ${{ secrets.DIGITALOCEAN_DOCKER_REGISTRY }}/code-execute-api:$(echo $GITHUB_SHA | head -c7)

  build-builder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build builder container image
      run: |
        cd builder
        docker build -f Dockerfile --build-arg USERNAME=${{ secrets.USERNAME }} --build-arg PASSWORD=${{ secrets.PASSWORD }} -t ${{ secrets.DIGITALOCEAN_DOCKER_REGISTRY }}/code-execute-builder:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run:  docker push ${{ secrets.DIGITALOCEAN_DOCKER_REGISTRY }}/code-execute-builder:$(echo $GITHUB_SHA | head -c7)

  build-exeuctor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build executor container image
      run: |
        cd executor
        docker build -f Dockerfile --build-arg USERNAME=${{ secrets.USERNAME }} --build-arg PASSWORD=${{ secrets.PASSWORD }} -t ${{ secrets.DIGITALOCEAN_DOCKER_REGISTRY }}/code-execute-executor:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run:  docker push ${{ secrets.DIGITALOCEAN_DOCKER_REGISTRY }}/code-execute-executor:$(echo $GITHUB_SHA | head -c7)


  build-try-out-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build try-out-script container image
      run: |
        cd executor
        docker build -f Dockerfile --build-arg USERNAME=${{ secrets.USERNAME }} --build-arg PASSWORD=${{ secrets.PASSWORD }} -t ${{ secrets.DIGITALOCEAN_DOCKER_REGISTRY }}/code-execute-try-out-script:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run:  docker push ${{ secrets.DIGITALOCEAN_DOCKER_REGISTRY }}/code-execute-try-out-script:$(echo $GITHUB_SHA | head -c7)




