apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: queue
  name: queue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/redis/
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: queue-secret
              key: redis-password
      volumes:
      - name: config
        configMap:
          name: queue-config
